name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      run: |
        # Cấp phép license vào thư mục SDK có sẵn của GitHub Actions
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo "24333f1a91d69192f1536b39de5522960f585d68" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131964887" >> $ANDROID_SDK_ROOT/licenses/android-sdk-license
        
        # Chạy build trực tiếp
        gradle assembleRelease

    - uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
