name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Generate Gradle Wrapper & Build
      run: |
        # Tự động tạo bộ công cụ gradlew ngay tại chỗ
        gradle wrapper --gradle-version 8.5
        
        # Cấp quyền thực thi và build
        chmod +x ./gradlew
        ./gradlew assembleRelease

    - uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
